### ISSUE TITLE
unterminated character set at position 3

### ISSUE THREAD

**Issue by pocketsnizort** [pocketsnizort/pythOCR#4]
```
python3 pythoCR.py --mode ocr "output\video.mp4"
INFO:root:Processing video.mp4, file 1 of 1
INFO:root:Using YoloCR in CLI mode.
INFO:root:Prelude.
INFO:root:Generating images
INFO:root:Generating alt images
INFO:root:OCRing images
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1115/1115 [00:29<00:00, 38.18it/s]
INFO:root:OCRing alt images
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 20.10it/s]
INFO:root:Correcting subtitles
Traceback (most recent call last):
  File "pythoCR.py", line 544, in <module>
    post_process_subs(subsdata, args.outputdir, file)
  File "pythoCR.py", line 399, in post_process_subs
    sub_data = check_sub_data(subsdata[0])
  File "pythoCR.py", line 256, in check_sub_data
    sub_data = extreme_try_subs_without_char(sub_data, args.heurist_char_replace, args.lang, word_count)
  File "pythoCR.py", line 112, in extreme_try_subs_without_char
    sub_data[idx] = (extreme_try_string_without_char(sub_data[idx][0], chars_to_try_to_replace, enchant_dict, word_count), sub_data[idx][1])
  File "pythoCR.py", line 103, in extreme_try_string_without_char
    for word in re.findall(r"\w+[" + re.escape("".join([char[0] for char in chars_to_try_to_replace])) + r"]\w+", string, flags=re.UNICODE):
  File "C:\Program Files (x86)\Python36-32\lib\re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
  File "C:\Program Files (x86)\Python36-32\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Program Files (x86)\Python36-32\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Program Files (x86)\Python36-32\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files (x86)\Python36-32\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files (x86)\Python36-32\lib\sre_parse.py", line 523, in _parse
    source.tell() - here)
sre_constants.error: unterminated character set at position 3
```

Note the absence of a config file.

**Comment by pocketsnizort** [comment]
bug showed up only if no heuristic char replace were given.
